closure_lm_981980
: 
Yk {src: html, Cg: {…}, C: 6}
closure_uid_230370336
: 
12
accessKey
: 
""
attributeStyleMap
: 
StylePropertyMap
size
: 
0
[[Prototype]]
: 
StylePropertyMap
attributes
: 
NamedNodeMap {0: lang, 1: dir, lang: lang, dir: dir, length: 2}
autocapitalize
: 
""
autofocus
: 
false
baseURI
: 
"https://sites.google.com/d/1rnRHEUqjU4Mswq1sieOP8AjgP-K3z-6Z/p/1Niw3uUn5YW3XwfmM_gaK_ql7K2C11gnH/edit"
childElementCount
: 
2
childNodes
: 
NodeList(2)
0
: 
head
1
: 
body.HB1eCd-UMrnmb.haDzEe.rzLfc.HB1eCd-HzV7m.EIlDfe
length
: 
2
[[Prototype]]
: 
NodeList
children
: 
HTMLCollection(2) [head, body.HB1eCd-UMrnmb.haDzEe.rzLfc.HB1eCd-HzV7m.EIlDfe]
classList
: 
DOMTokenList [value: '']
className
: 
""
clientHeight
: 
520
clientLeft
: 
0
clientTop
: 
0
clientWidth
: 
584
contentEditable
: 
"inherit"
dataset
: 
DOMStringMap {}
dir
: 
"ltr"
draggable
: 
false
elementTiming
: 
""
enterKeyHint
: 
""
firstChild
: 
head
firstElementChild
: 
head
hidden
: 
false
id
: 
""
inert
: 
false
innerHTML
: 
"<head><script src=\"https://apis.google.com/_/scs
innerText
: 
"Sites home\nSite document name\nUndo last action\nUndo last action\nRedo last action\nRedo last action\nPreview\nPreview\nCan't copy link for unpublished site\nCan't copy link for unpublished site\nShare with others\nShare with others\nSettings\nSettings\nMore\nPublish\nNavigation settings\nAdd logo\nEdit this menu via the Pages tabSHOW ME\nDelete header\nImage\nReset\nHeader type\n[Name]'s Learning Journey\nSection colors\nDuplicate section\nDelete section\n\n \n\nSection colors\nDuplicate section\nDelete section\nAbout Me\n\n\n\n\nTell your site viewers more about yourself.\n\nWhat grade are you in and what school do you go to?\n\nWhat skills, talents, and knowledge do you have? What do you like learning about?\n\nSection colors\nDuplicate section\nDelete section\n\n \n\nSection colors\nDuplicate section\nDelete section\n\n \n\nSection colors\nDuplicate section\nDelete section\nAchievements\n\nWhat achievements are you proud of?\n\nStrengths\n\nWhat are some of your strengths?\n\nGoals\n\nWhat skills are you working on?\n\nSection colors\nDuplicate section\nDelete section\nAchievements\n\nWhat achievements are you proud of?\n\nStrengths\n\nWhat are some of your strengths?\n\nGoals\n\nWhat skills are you working on?\n\nSection colors\nDuplicate section\nDelete section\n\n \n\nEdit footer\nGet in touch at [email address]\nExpanded "
inputMode
: 
""
isConnected
: 
true
isContentEditable
: 
false
lang
: 
"en"
lastChild
: 
body.HB1eCd-UMrnmb.haDzEe.rzLfc.HB1eCd-HzV7m.EIlDfe
lastElementChild
: 
body.HB1eCd-UMrnmb.haDzEe.rzLfc.HB1eCd-HzV7m.EIlDfe
localName
: 
"html"
namespaceURI
: 
"http://www.w3.org/1999/xhtml"
nodeName
: 
"HTML"
nodeType
: 
1
nonce
: 
""
offsetHeight
: 
520
offsetLeft
: 
0
offsetTop
: 
0
offsetWidth
: 
584
outerHTML
: 
"<html lang=\"en\" dir=\"ltr\"><head><script src=\
outerText
: 
"Sites home\nSite document name\nUndo last action\nUndo last action\nRedo last action\nRedo last action\nPreview\nPreview\nCan't copy link for unpublished site\nCan't copy link for unpublished site\nShare with others\nShare with others\nSettings\nSettings\nMore\nPublish\nNavigation settings\nAdd logo\nEdit this menu via the Pages tabSHOW ME\nDelete header\nImage\nReset\nHeader type\n[Name]'s Learning Journey\nSection colors\nDuplicate section\nDelete section\n\n \n\nSection colors\nDuplicate section\nDelete section\nAbout Me\n\n\n\n\nTell your site viewers more about yourself.\n\nWhat grade are you in and what school do you go to?\n\nWhat skills, talents, and knowledge do you have? What do you like learning about?\n\nSection colors\nDuplicate section\nDelete section\n\n \n\nSection colors\nDuplicate section\nDelete section\n\n \n\nSection colors\nDuplicate section\nDelete section\nAchievements\n\nWhat achievements are you proud of?\n\nStrengths\n\nWhat are some of your strengths?\n\nGoals\n\nWhat skills are you working on?\n\nSection colors\nDuplicate section\nDelete section\nAchievements\n\nWhat achievements are you proud of?\n\nStrengths\n\nWhat are some of your strengths?\n\nGoals\n\nWhat skills are you working on?\n\nSection colors\nDuplicate section\nDelete section\n\n \n\nEdit footer\nGet in touch at [email address]\nExpanded "
ownerDocument
: 
document
parentNode
: 
document
part
: 
DOMTokenList [value: '']
previousSibling
: 
<!DOCTYPE html>
scrollHeight
: 
520
scrollLeft
: 
0
scrollTop
: 
0
scrollWidth
: 
584
slot
: 
""
spellcheck
: 
true
style
: 
CSSStyleDeclaration {accentColor: '', additiveSymbols: '', alignContent: '', alignItems: '', alignSelf: '', …}
tabIndex
: 
-1
tagName
: 
"HTML"
textContent
: 
"var DOCS_timing={}; DOCS_timing['sl']=new Date().
title
: 
""
translate
: 
true
version
: 
""
virtualKeyboardPolicy
: 
""
writingSuggestions
: 
"true"
